# Generated by Django 4.2.16 on 2024-10-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='about/')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('information', models.TextField(verbose_name='information')),
                ('information_uz', models.TextField(null=True, verbose_name='information')),
                ('information_ru', models.TextField(null=True, verbose_name='information')),
                ('information_en', models.TextField(null=True, verbose_name='information')),
                ('image', models.ImageField(upload_to='certificate/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=212, verbose_name='full_name')),
                ('image', models.ImageField(upload_to='feedback/')),
                ('profession', models.CharField(max_length=212, verbose_name='profession')),
                ('profession_uz', models.CharField(max_length=212, null=True, verbose_name='profession')),
                ('profession_ru', models.CharField(max_length=212, null=True, verbose_name='profession')),
                ('profession_en', models.CharField(max_length=212, null=True, verbose_name='profession')),
                ('message', models.TextField(verbose_name='message')),
                ('message_uz', models.TextField(null=True, verbose_name='message')),
                ('message_ru', models.TextField(null=True, verbose_name='message')),
                ('message_en', models.TextField(null=True, verbose_name='message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('title_uz', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('tick', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='partnership/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(upload_to='social_media/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=212, verbose_name='full_name')),
                ('phone_number', models.CharField(max_length=212)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('title_uz', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=125, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=212, verbose_name='full_name')),
                ('occupation', models.CharField(max_length=212)),
                ('occupation_uz', models.CharField(max_length=212, null=True)),
                ('occupation_ru', models.CharField(max_length=212, null=True)),
                ('occupation_en', models.CharField(max_length=212, null=True)),
                ('image', models.ImageField(upload_to='team/')),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212)),
                ('title_uz', models.CharField(max_length=212, null=True)),
                ('title_ru', models.CharField(max_length=212, null=True)),
                ('title_en', models.CharField(max_length=212, null=True)),
                ('image', models.ImageField(upload_to='service/')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_info', to='main.services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=212, verbose_name='title')),
                ('title_uz', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=212, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='project/')),
                ('link', models.URLField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services')),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('title_uz', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=125, null=True, verbose_name='title')),
                ('price', models.FloatField()),
                ('limit_date', models.CharField(max_length=125)),
                ('limit_user', models.CharField(max_length=125)),
                ('features', models.ManyToManyField(to='main.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=212, verbose_name='full_name')),
                ('phone_number', models.CharField(max_length=212)),
                ('is_checked', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(verbose_name='question')),
                ('question_uz', models.TextField(null=True, verbose_name='question')),
                ('question_ru', models.TextField(null=True, verbose_name='question')),
                ('question_en', models.TextField(null=True, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faqtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
